// <auto-generated />
using System;
using Backend.ATM.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.ATM.Infrastructure.Migrations
{
    [DbContext(typeof(AtmDbContext))]
    partial class AtmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.ATM.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "100000000001",
                            Balance = 1500.00m,
                            CreatedAt = new DateTime(2026, 1, 10, 8, 30, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            CustomerName = "John Doe",
                            Status = "Active",
                            Version = 0L
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "100000000002",
                            Balance = 2750.50m,
                            CreatedAt = new DateTime(2026, 1, 11, 9, 45, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            CustomerName = "Jane Smith",
                            Status = "Active",
                            Version = 0L
                        });
                });

            modelBuilder.Entity("Backend.ATM.Domain.Entities.AtmMachine", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("CashAvailable")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("MaxWithdrawalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MachineCode")
                        .IsUnique();

                    b.ToTable("AtmMachines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CashAvailable = 50000m,
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            LastMaintenanceDate = new DateTime(2026, 1, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            Location = "12 Marina Road, Lagos",
                            MachineCode = "ATM-LAG-001",
                            MaxWithdrawalAmount = 1000m,
                            Status = "Online",
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CashAvailable = 25000m,
                            CreatedAt = new DateTime(2026, 1, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            LastMaintenanceDate = new DateTime(2026, 1, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Location = "45 Central Business District, Abuja",
                            MachineCode = "ATM-ABJ-002",
                            MaxWithdrawalAmount = 1000m,
                            Status = "Offline",
                            UpdatedAt = new DateTime(2026, 1, 16, 9, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Backend.ATM.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "SeedCreated",
                            Changes = "Initial account seed created with opening balance 5000.00 USD.",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 15, 0, 0, DateTimeKind.Utc),
                            EntityId = 1,
                            EntityType = "Account",
                            IpAddress = "127.0.0.1",
                            PerformedBy = "SystemSeed",
                            Timestamp = new DateTime(2026, 1, 10, 8, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Action = "SeedCreated",
                            Changes = "ATM machine ATM-LAG-001 seeded as Online with cash available 50000.00.",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 20, 0, 0, DateTimeKind.Utc),
                            EntityId = 1,
                            EntityType = "AtmMachine",
                            IpAddress = "127.0.0.1",
                            PerformedBy = "SystemSeed",
                            Timestamp = new DateTime(2026, 1, 10, 8, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Action = "StatusReviewed",
                            Changes = "Seeded card linked to Account 2 verified for initial active status.",
                            CreatedAt = new DateTime(2026, 1, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = 2,
                            EntityType = "Card",
                            IpAddress = "127.0.0.1",
                            PerformedBy = "SystemSeed",
                            Timestamp = new DateTime(2026, 1, 11, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Backend.ATM.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BlockedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyWithdrawalLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedPinAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastFailedAttempt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 8, 45, 0, 0, DateTimeKind.Utc),
                            DailyWithdrawalLimit = 1000,
                            ExpiryDate = new DateTime(2029, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            FailedPinAttempts = 0,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            CreatedAt = new DateTime(2026, 1, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            DailyWithdrawalLimit = 1500,
                            ExpiryDate = new DateTime(2030, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FailedPinAttempts = 0,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Backend.ATM.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("EntryDate");

                    b.HasIndex("TransactionId");

                    b.ToTable("LedgerEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Amount = 200.00m,
                            BalanceAfter = 1300.00m,
                            CreatedAt = new DateTime(2026, 4, 5, 9, 1, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Ledger entry for ATM cash withdrawal",
                            EntryDate = new DateTime(2026, 4, 5, 9, 1, 0, 0, DateTimeKind.Utc),
                            EntryType = "Debit",
                            TransactionId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Amount = 0.00m,
                            BalanceAfter = 800.00m,
                            CreatedAt = new DateTime(2026, 4, 5, 9, 15, 30, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Ledger entry for ATM balance inquiry",
                            EntryDate = new DateTime(2026, 4, 5, 9, 15, 30, 0, DateTimeKind.Utc),
                            EntryType = "Credit",
                            TransactionId = 2
                        });
                });

            modelBuilder.Entity("Backend.ATM.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AtmMachineId")
                        .HasColumnType("int");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AtmMachineId");

                    b.HasIndex("CardId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TransactionReference")
                        .IsUnique();

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Amount = 200.00m,
                            AtmMachineId = 1,
                            BalanceAfter = 1300.00m,
                            BalanceBefore = 1500.00m,
                            CardId = 1,
                            CompletedAt = new DateTime(2026, 4, 5, 9, 1, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 4, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "ATM cash withdrawal",
                            Status = "Completed",
                            TransactionReference = "TXN-20260405-0001",
                            Type = "Withdrawal",
                            UpdatedAt = new DateTime(2026, 4, 5, 9, 1, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Amount = 0.00m,
                            AtmMachineId = 1,
                            BalanceAfter = 800.00m,
                            BalanceBefore = 800.00m,
                            CardId = 2,
                            CompletedAt = new DateTime(2026, 4, 5, 9, 15, 30, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 4, 5, 9, 15, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "ATM balance inquiry",
                            Status = "Completed",
                            TransactionReference = "TXN-20260405-0002",
                            Type = "BalanceInquiry",
                            UpdatedAt = new DateTime(2026, 4, 5, 9, 15, 30, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Backend.ATM.Domain.Entities.Card", b =>
                {
                    b.HasOne("Backend.ATM.Domain.Entities.Account", "Account")
                        .WithMany("Cards")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Backend.ATM.Domain.ValueObjects.CardNumber", "CardNumber", b1 =>
                        {
                            b1.Property<int>("CardId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(19)
                                .HasColumnType("nvarchar(19)")
                                .HasColumnName("CardNumber");

                            b1.HasKey("CardId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Cards");

                            b1.WithOwner()
                                .HasForeignKey("CardId");

                            b1.HasData(
                                new
                                {
                                    CardId = 1,
                                    Value = "4532015112830366"
                                },
                                new
                                {
                                    CardId = 2,
                                    Value = "4485275742308327"
                                });
                        });

                    b.OwnsOne("Backend.ATM.Domain.ValueObjects.Pin", "Pin", b1 =>
                        {
                            b1.Property<int>("CardId")
                                .HasColumnType("int");

                            b1.Property<string>("HashedValue")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("HashedPin");

                            b1.HasKey("CardId");

                            b1.ToTable("Cards");

                            b1.WithOwner()
                                .HasForeignKey("CardId");

                            b1.HasData(
                                new
                                {
                                    CardId = 1,
                                    HashedValue = "$2a$11$M/8cXrN0bGfYfK7xO6jM3eQq8u0Jw3xVQxQ5vWlA9QvHjQ9mYwY7K"
                                },
                                new
                                {
                                    CardId = 2,
                                    HashedValue = "$2a$11$7oQZ0JrM0QeWmP4nJbFQ7uRj0n0f7V8cZrJQm9sLQvN2aXbT8cD1G"
                                });
                        });

                    b.Navigation("Account");

                    b.Navigation("CardNumber")
                        .IsRequired();

                    b.Navigation("Pin")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.ATM.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("Backend.ATM.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.ATM.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Backend.ATM.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Backend.ATM.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.ATM.Domain.Entities.AtmMachine", "AtmMachine")
                        .WithMany()
                        .HasForeignKey("AtmMachineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.ATM.Domain.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("AtmMachine");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Backend.ATM.Domain.Entities.Account", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
